# Generated by Django 5.2.8 on 2025-11-11 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('konten_narasi', models.TextField()),
                ('urutan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('urutan', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_aktivitas', models.CharField(choices=[('PILIHAN_GANDA', 'Pilihan Ganda'), ('PUZZLE_CODE', 'Puzzle Susun Kode'), ('DEMO_HTML', 'Demo HTML Live')], max_length=20)),
                ('instruksi', models.TextField(help_text='Jelaskan apa yang harus dilakukan siswa.')),
                ('poin', models.IntegerField(default=20)),
                ('kode_jawaban', models.TextField(blank=True, help_text='Tulis kode jawaban yang benar dalam satu baris, tanpa spasi.', null=True)),
                ('blok_kode_acak', models.TextField(blank=True, help_text='Tulis blok kode, pisahkan dengan koma. Contoh: <p>,Halo Dunia,</p>', null=True)),
                ('validasi_html', models.CharField(blank=True, help_text='Tag HTML yang harus ada di jawaban. Contoh: <b>', max_length=100, null=True)),
                ('materi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas', to='api.materi')),
            ],
        ),
        migrations.AddField(
            model_name='materi',
            name='modul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modul'),
        ),
        migrations.CreateModel(
            name='Lencana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=255)),
                ('modul_terkait', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.modul')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_poin', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HasilAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.IntegerField()),
                ('tanggal_pengerjaan', models.DateTimeField(auto_now_add=True)),
                ('aktivitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aktivitas')),
                ('profil_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profilsiswa')),
            ],
        ),
        migrations.CreateModel(
            name='SoalPilihanGanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('aktivitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal_pilgan', to='api.aktivitas')),
            ],
        ),
        migrations.CreateModel(
            name='PilihanJawaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_jawaban', models.CharField(max_length=255)),
                ('apakah_benar', models.BooleanField(default=False)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan', to='api.soalpilihanganda')),
            ],
        ),
        migrations.CreateModel(
            name='MateriSelesai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_selesai', models.DateTimeField(auto_now_add=True)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materi')),
                ('profil_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profilsiswa')),
            ],
            options={
                'unique_together': {('profil_siswa', 'materi')},
            },
        ),
        migrations.CreateModel(
            name='LencanaSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_didapat', models.DateTimeField(auto_now_add=True)),
                ('lencana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lencana')),
                ('profil_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profilsiswa')),
            ],
            options={
                'unique_together': {('profil_siswa', 'lencana')},
            },
        ),
    ]
