# Generated by Django 5.2.8 on 2025-11-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lencana',
            name='jenis',
            field=models.CharField(choices=[('MODULE_COMPLETE', 'Selesaikan Modul'), ('QUIZ_COUNT', 'Jumlah Quiz Selesai')], default='MODULE_COMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='lencana',
            name='syarat_quiz_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
