# Generated by Django 5.2.8 on 2025-12-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lencana_jenis_lencana_syarat_quiz_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='materi_pdf'),
        ),
        migrations.AddField(
            model_name='profilsiswa',
            name='kelas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilsiswa',
            name='nisn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
